### ISSUE TITLE
ODBC errror code 10

### ISSUE THREAD

**Issue by kganczuk** [sitemule/noxDB#19]
Hello, 

I've tried to run one program from examples (A.rpgle) and I got following error:

> Message ID . . . . . . :   SQ99999       Severity . . . . . . . :   30        
> Message type . . . . . :   Diagnostic                                         
> Date sent  . . . . . . :   27/06/19      Time sent  . . . . . . :   11:35:30  
>                                                                               
> Message . . . . :   Error occurred in SQL Call Level Interface                
> Cause . . . . . :   A procedure call encountered an error.  The error code is 
>   10. Error codes are:                                                                                               
>     10 -- Function sequence error.                                            
>  Recovery  . . . :   Refer to the DB2 for i SQL Call Level Interface (ODBC)       
>   topic collection in the Database category in the IBM i Information Center 
>   book for a complete description of the error. Specifically, look at the   
>   procedure that sent the error.                                            
                                                                                                          
It happens after this statement:
` pRows = json_sqlResultSet(sql:start:limit:JSON_META+JSON_FIELDS);`

**Comment by NielsLiisberg** [comment]
Typical this happens when you debug and stop and the restart all over. or
you reclaim rout resources with out a json_sqldisconnect();

If not run from within ILEastic or other multithreaded environment, then
use a construction like below to ensure the sequense of statements are :

json_sqlConnect(...);
pRows = json_sqlResultSet(sql:start:limit:JSON_META+JSON_FIELDS);
json_sqlDisconnect(...);



In your current setup you can do either:

Signoff and on

Or do

RCLACTGRP QILE
RCLACTGRP QSQCLI

**Comment by kganczuk** [comment]
json_sqlConnect helped, thanks 👍
